package vical.com.pe.myapp.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LISTA.
 */
public class Lista {

    private Long id;
    /** Not-null value. */
    private String Codigo;
    private String Nomnbre;
    private String Descripcion;
    private String Valor;

    public Lista() {
    }

    public Lista(Long id) {
        this.id = id;
    }

    public Lista(Long id, String Codigo, String Nomnbre, String Descripcion, String Valor) {
        this.id = id;
        this.Codigo = Codigo;
        this.Nomnbre = Nomnbre;
        this.Descripcion = Descripcion;
        this.Valor = Valor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCodigo() {
        return Codigo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getNomnbre() {
        return Nomnbre;
    }

    public void setNomnbre(String Nomnbre) {
        this.Nomnbre = Nomnbre;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getValor() {
        return Valor;
    }

    public void setValor(String Valor) {
        this.Valor = Valor;
    }

}
