package vical.com.pe.myapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import vical.com.pe.myapp.entity.User;
import vical.com.pe.myapp.entity.Lista;
import vical.com.pe.myapp.entity.Valor;

import vical.com.pe.myapp.dao.UserDao;
import vical.com.pe.myapp.dao.ListaDao;
import vical.com.pe.myapp.dao.ValorDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig listaDaoConfig;
    private final DaoConfig valorDaoConfig;

    private final UserDao userDao;
    private final ListaDao listaDao;
    private final ValorDao valorDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        listaDaoConfig = daoConfigMap.get(ListaDao.class).clone();
        listaDaoConfig.initIdentityScope(type);

        valorDaoConfig = daoConfigMap.get(ValorDao.class).clone();
        valorDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        listaDao = new ListaDao(listaDaoConfig, this);
        valorDao = new ValorDao(valorDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Lista.class, listaDao);
        registerDao(Valor.class, valorDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        listaDaoConfig.getIdentityScope().clear();
        valorDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ListaDao getListaDao() {
        return listaDao;
    }

    public ValorDao getValorDao() {
        return valorDao;
    }

}
