package vical.com.pe.myapp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import vical.com.pe.myapp.entity.Lista;

import vical.com.pe.myapp.entity.Valor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VALOR.
*/
public class ValorDao extends AbstractDao<Valor, Long> {

    public static final String TABLENAME = "VALOR";

    /**
     * Properties of entity Valor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ListaId = new Property(0, Long.class, "listaId", false, "LISTA_ID");
        public final static Property Id = new Property(1, Long.class, "id", true, "_id");
        public final static Property Codigo = new Property(2, String.class, "Codigo", false, "CODIGO");
        public final static Property Nomnbre = new Property(3, String.class, "Nomnbre", false, "NOMNBRE");
        public final static Property Descripcion = new Property(4, String.class, "Descripcion", false, "DESCRIPCION");
        public final static Property Valor = new Property(5, String.class, "Valor", false, "VALOR");
    };

    private DaoSession daoSession;


    public ValorDao(DaoConfig config) {
        super(config);
    }
    
    public ValorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VALOR' (" + //
                "'LISTA_ID' INTEGER," + // 0: listaId
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 1: id
                "'CODIGO' TEXT NOT NULL ," + // 2: Codigo
                "'NOMNBRE' TEXT," + // 3: Nomnbre
                "'DESCRIPCION' TEXT," + // 4: Descripcion
                "'VALOR' TEXT);"); // 5: Valor
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VALOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Valor entity) {
        stmt.clearBindings();
 
        Long listaId = entity.getListaId();
        if (listaId != null) {
            stmt.bindLong(1, listaId);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
        stmt.bindString(3, entity.getCodigo());
 
        String Nomnbre = entity.getNomnbre();
        if (Nomnbre != null) {
            stmt.bindString(4, Nomnbre);
        }
 
        String Descripcion = entity.getDescripcion();
        if (Descripcion != null) {
            stmt.bindString(5, Descripcion);
        }
 
        String Valor = entity.getValor();
        if (Valor != null) {
            stmt.bindString(6, Valor);
        }
    }

    @Override
    protected void attachEntity(Valor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public Valor readEntity(Cursor cursor, int offset) {
        Valor entity = new Valor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // listaId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.getString(offset + 2), // Codigo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Nomnbre
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Descripcion
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // Valor
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Valor entity, int offset) {
        entity.setListaId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCodigo(cursor.getString(offset + 2));
        entity.setNomnbre(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDescripcion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setValor(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Valor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Valor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getListaDao().getAllColumns());
            builder.append(" FROM VALOR T");
            builder.append(" LEFT JOIN LISTA T0 ON T.'LISTA_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Valor loadCurrentDeep(Cursor cursor, boolean lock) {
        Valor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Lista lista = loadCurrentOther(daoSession.getListaDao(), cursor, offset);
        entity.setLista(lista);

        return entity;    
    }

    public Valor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Valor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Valor> list = new ArrayList<Valor>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Valor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Valor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
